[package]
name = "apex-pty"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
apex-proto.workspace = true

anyhow.workspace = true
bytes.workspace = true
portable-pty = "0.9"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
