import {
  Activity,
  ArrowDownToLine,
  ArrowRightLeft,
  ArrowUpFromLine,
  Atom,
  Bell,
  BellOff,
  BookMarked,
  Bot,
  Braces,
  Brain,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleHelp,
  CirclePlay,
  CircleStop,
  Columns2,
  Combine,
  Cpu,
  Database,
  ExternalLink,
  File,
  FileArchive,
  FileCode,
  FileCog,
  FileImage,
  FileJson,
  FileLock,
  FileText,
  Folder,
  FolderGit,
  Gem,
  GitBranch,
  Globe,
  Gpu,
  History,
  House,
  Inbox,
  Keyboard,
  KeyRound,
  LayoutGrid,
  type LucideIcon,
  MemoryStick,
  Microchip,
  Monitor,
  Moon,
  MoveHorizontal,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  PencilRuler,
  Plus,
  RefreshCw,
  Rocket,
  Rows3,
  Save,
  Search,
  Send,
  Settings2,
  Sparkles,
  SquareSplitHorizontal,
  SquareSplitVertical,
  SquareTerminal,
  Sun,
  Undo2,
  Wrench,
  X,
} from "lucide-preact";

const ICONS = {
  settings: Settings2,
  plus: Plus,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  refresh: RefreshCw,
  save: Save,
  revert: Undo2,
  close: X,
  chevron: ChevronDown,
  panel: PanelLeft,
  panelClose: PanelLeftClose,
  panelOpen: PanelLeftOpen,
  activity: Activity,
  bell: Bell,
  bellOff: BellOff,
  sessions: SquareTerminal,
  files: Folder,
  branch: GitBranch,
  pull: ArrowDownToLine,
  push: ArrowUpFromLine,
  history: History,
  home: House,
  send: Send,
  inbox: Inbox,
  combine: Combine,
  wrench: Wrench,
  move: MoveHorizontal,
  context: BookMarked,
  play: CirclePlay,
  stop: CircleStop,
  check: Check,
  circle: Circle,
  file: File,
  external: ExternalLink,
  cpu: Cpu,
  gpu: Gpu,
  memory: MemoryStick,
  swap: ArrowRightLeft,
  keyboard: Keyboard,
  grid: LayoutGrid,
  externalApp: PencilRuler,
  pencil: Pencil,
  splitRight: SquareSplitHorizontal,
  splitDown: SquareSplitVertical,
  columns: Columns2,
  microchip: Microchip,
  rows: Rows3,
  sparkles: Sparkles,
  bot: Bot,
  help: CircleHelp,
  braces: Braces,
  rocket: Rocket,
  brain: Brain,
  atom: Atom,
  gem: Gem,
  fileCode: FileCode,
  fileJson: FileJson,
  fileText: FileText,
  fileCog: FileCog,
  fileLock: FileLock,
  secret: KeyRound,
  fileImage: FileImage,
  fileArchive: FileArchive,
  database: Database,
  folderGit: FolderGit,
  globe: Globe,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  search: Search,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

type Props = {
  name: IconName;
  size?: number;
  class?: string;
};

export function Icon({ name, size = 14, class: className }: Props) {
  const Glyph = ICONS[name];
  return <Glyph size={size} strokeWidth={1.75} aria-hidden="true" class={className} />;
}
