import {
  Activity,
  ArrowRightLeft,
  Atom,
  Bell,
  BellOff,
  BookMarked,
  Bot,
  Braces,
  Brain,
  Check,
  ChevronDown,
  CirclePlay,
  CircleStop,
  Combine,
  Cpu,
  Database,
  ExternalLink,
  File,
  FileArchive,
  FileCode,
  FileCog,
  FileImage,
  FileJson,
  FileLock,
  FileText,
  Folder,
  FolderGit,
  Gem,
  GitBranch,
  Gpu,
  History,
  Keyboard,
  type LucideIcon,
  MemoryStick,
  Monitor,
  Moon,
  MoveHorizontal,
  PanelLeft,
  PencilRuler,
  Plus,
  RefreshCw,
  Rocket,
  Settings2,
  Sparkles,
  SquareSplitHorizontal,
  SquareSplitVertical,
  SquareTerminal,
  Sun,
  X,
} from "lucide-preact";

const ICONS = {
  settings: Settings2,
  plus: Plus,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  refresh: RefreshCw,
  close: X,
  chevron: ChevronDown,
  panel: PanelLeft,
  activity: Activity,
  bell: Bell,
  bellOff: BellOff,
  sessions: SquareTerminal,
  files: Folder,
  branch: GitBranch,
  history: History,
  combine: Combine,
  move: MoveHorizontal,
  context: BookMarked,
  play: CirclePlay,
  stop: CircleStop,
  check: Check,
  file: File,
  external: ExternalLink,
  cpu: Cpu,
  gpu: Gpu,
  memory: MemoryStick,
  swap: ArrowRightLeft,
  keyboard: Keyboard,
  externalApp: PencilRuler,
  splitRight: SquareSplitHorizontal,
  splitDown: SquareSplitVertical,
  sparkles: Sparkles,
  bot: Bot,
  braces: Braces,
  rocket: Rocket,
  brain: Brain,
  atom: Atom,
  gem: Gem,
  fileCode: FileCode,
  fileJson: FileJson,
  fileText: FileText,
  fileCog: FileCog,
  fileLock: FileLock,
  fileImage: FileImage,
  fileArchive: FileArchive,
  database: Database,
  folderGit: FolderGit,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

type Props = {
  name: IconName;
  size?: number;
  class?: string;
};

export function Icon({ name, size = 14, class: className }: Props) {
  const Glyph = ICONS[name];
  return <Glyph size={size} strokeWidth={1.75} aria-hidden="true" class={className} />;
}
